service: shopfast-api

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev

  environment:
    USER_POOL_ID: !ImportValue ShopFast-UserPoolId
    USER_POOL_CLIENT_ID: !ImportValue ShopFast-UserPoolClientIdA

# =========================
# HTTP API configuration
# =========================
httpApi:
  cors: true
  authorizers:
    cognitoAuthorizer:
      type: cognito
      userPoolArn: !ImportValue ShopFast-UserPoolArn

functions:
  createPayment:
    handler: src/handler.create_payment
    events:
      - httpApi:
          path: /payments/create
          method: POST
          authorizer:
            name: cognitoAuthorizer
            scopes:
              - payment-service/payments.create

  refundPayment:
    handler: src/handler.refund_payment
    events:
      - httpApi:
          path: /payments/refund
          method: POST
          authorizer:
            name: cognitoAuthorizer
            scopes:
              - payment-service/payments.refund

resources:
  Resources:
    ApiCustomDomain:
      Type: AWS::ApiGatewayV2::DomainName
      Properties:
        DomainName: api-dev.denilparmar.work
        DomainNameConfigurations:
          - CertificateArn: ${cf:shopfast-api-cert-dev.ShopFastApiCertificateArn}
            EndpointType: EDGE

    ApiBasePathMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties:
        ApiId: !Ref HttpApi
        DomainName: !Ref ApiCustomDomain
        Stage: ${self:provider.stage}
        ApiMappingKey: ''
