name: Deploy ShopFast API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
      USER_POOL_CLIENT_ID: ${{ secrets.USER_POOL_CLIENT_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Node dependencies
        run: npm install --legacy-peer-deps

      - name: Install Python dependencies for Lambdas
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r src/requirements.txt -t src

      - name: Build TypeScript CDK
        run: |
          cd shopfast-api-cdk
          npx tsc

      - name: Bootstrap CDK (if first time)
        run: |
          cd shopfast-api-cdk
          npx cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION

      - name: Deploy CDK Stack
        run: |
          cd shopfast-api-cdk
          npx cdk deploy ShopfastApiStack --require-approval never
